<?php
require('./content/srcpdf/fpdf.php');
require('./con/koneksi.php');
require('./con/function.php');
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B','10');
$pdf->Cell(0,20, 'PT Media Andalan Nusa (Nusanet)', '0', 1, 'R');
$pdf->SetFont('Arial','B','14');
$pdf->Cell(0,10, 'FORMULIR PENDAFTRAN', '0', 5, 'C');
$pdf->Ln();
$pdf->SetFont('Arial','B','10');
$pdf->Cell(0,7, 'DATA PELANGGAN', '0', 1, 'L');
$pdf->Ln();
$pdf->SetFont('Arial','','10');
$pdf->Cell(0,7, 'Jenis Pendaftaran        : Baru', '0', 1, 'L');
$pdf->Cell(0,7, 'Nama Lengkap             : John Dor', '0', 1, 'L');
$pdf->Cell(0,7, 'No ID Pelanggan          : 8595768', '0', 1, 'L');
$pdf->Cell(0,7, 'Alamat Pemasangan    : Simprug Residence, Blok 3C No 10, Jl. Teuku Nyak Arief, Jakarta Selatan', '0', 1, 'L');
$pdf->Cell(0,7, 'Nomor Telepon             : 0895634748', '0', 1, 'L');
$pdf->Ln();
$pdf->SetFont('Arial','B','10');
$pdf->Cell(0,7, 'LAYANAN', '0', 1, 'L');
$pdf->Ln();
$pdf->SetFont('Arial','','10');
$pdf->Cell(0,7, 'Jenis Layanan               : Paket Diamond', '0', 1, 'L');
$pdf->Cell(0,7, 'Layanan Tembahan      : No', '0', 1, 'L');
$pdf->Cell(0,7, 'Nomor SN STB             : 2323-36474-56788', '0', 1, 'L');
$pdf->Cell(0,7, 'Alamat Email                 : john@doe.com', '0', 1, 'L');
$pdf->Cell(0,7, 'Kata Sandi                    :', '0', 1, 'L');
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial','B','10');
$pdf->Cell(0,7, 'Tanggal : 08 Maret 2015', '0', 1, 'R');
$pdf->SetFont('Arial','','10');
$pdf->Cell(0,7, 'Tanda Tangan', '0', 1, 'R');
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Image('./img/tanda_tangan.jpg','165','190','33','33');
$pdf->SetFont('Arial','','10');
$pdf->Cell(0,7, 'John Doe              ', '0', 1, 'R');
$pdf->Cell(0,7, 'Customer Relation Officer', '0', 1, 'R');
$pdf->Cell(0,7, 'PT Media Andalan Nusa ', '0', 1, 'R');

$pdf->output();
?>
